//! Regenerates the committed public-API surface snapshots
//! (`docs/public-api/<crate>.txt`, one per published crate) on every
//! `cargo test` run, so API changes always show up as a git diff next to the
//! code change that caused them, and the surface size stays one glance away.
//!
//! Modes (`ZEN_API_DOC` env var — set per-job in CI workflows, see ci.yml):
//! - unset / `regen` → regenerate the files in place (local default; commit the diff)
//! - `check`         → regenerate to memory, FAIL if a committed file is stale
//! - `off`           → skipped (CI matrix jobs without nightly rustdoc / the tool)
//!
//! Requires `cargo-public-api` (0.52+) and a nightly toolchain for rustdoc
//! JSON: `cargo install cargo-public-api --locked && rustup toolchain install nightly`
//! The default feature set includes `asm`, so regeneration also needs NASM on
//! PATH (same as any default build of this crate).

use std::path::PathBuf;
use std::process::Command;

/// Published crates in this workspace (`ivf` is `publish = false`).
///
/// The bool is "include the all-features section". zenrav1e is snapshotted
/// with default features only:
/// - `decode_test` / `decode_test_dav1d` (aom-sys / dav1d-sys) link system
///   libaom/libdav1d, which CI runners and contributor machines don't
///   reliably have;
/// - `capi` documents `src/capi.rs`, which the include-list excludes from the
///   published package (`!/src/capi.rs`) — its surface would be a lie for
///   crates.io consumers (it ships via cargo-c builds instead);
/// - `bench` exposes ~800 internal benchmark helpers that are not user API.
const CRATES: &[(&str, bool)] = &[("zenrav1e", false)];

fn run(args: &[&str]) -> Vec<u8> {
  let out = Command::new("cargo")
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .args(args)
        .output()
        .unwrap_or_else(|e| {
            panic!(
                "failed to run cargo {} ({e}); for public-api: install with \
                 `cargo install cargo-public-api --locked` and ensure a nightly \
                 toolchain exists (`rustup toolchain install nightly`), or set \
                 ZEN_API_DOC=off to skip this test",
                args[0]
            )
        });
  assert!(
    out.status.success(),
    "cargo {} failed (set ZEN_API_DOC=off to skip):\n{}",
    args.join(" "),
    String::from_utf8_lossy(&out.stderr)
  );
  out.stdout
}

fn surface(package: &str, feature_args: &[&str]) -> Vec<String> {
  let mut args = vec!["public-api", "-p", package, "--simplified"];
  args.extend_from_slice(feature_args);
  String::from_utf8(run(&args))
    .expect("cargo public-api emitted non-UTF8")
    .lines()
    .map(str::to_owned)
    .filter(|l| !l.is_empty())
    .collect()
}

/// All manifest features of `package` except `default` and underscore-
/// prefixed internal gates, sorted for determinism.
fn public_features(package: &str) -> Vec<String> {
  let meta: serde_json::Value = serde_json::from_slice(&run(&[
    "metadata",
    "--no-deps",
    "--format-version",
    "1",
  ]))
  .expect("cargo metadata JSON");
  let pkg = meta["packages"]
    .as_array()
    .expect("packages array")
    .iter()
    .find(|p| p["name"] == package)
    .unwrap_or_else(|| panic!("{package} not in workspace metadata"));
  let mut feats: Vec<String> = pkg["features"]
    .as_object()
    .expect("features map")
    .keys()
    .filter(|k| *k != "default" && !k.starts_with('_'))
    .cloned()
    .collect();
  feats.sort();
  feats
}

#[test]
fn public_api_surface_docs_are_current() {
  match std::env::var("ZEN_API_DOC").as_deref() {
    Ok("off") => {
      eprintln!(
        "ZEN_API_DOC=off — public-API snapshot regen skipped by caller"
      );
      return;
    }
    Ok("check") | Ok("regen") | Err(_) => {}
    Ok(other) => {
      panic!("unknown ZEN_API_DOC value {other:?} (off|check|regen)")
    }
  }
  let check = std::env::var("ZEN_API_DOC").as_deref() == Ok("check");

  for &(package, all_features_section) in CRATES {
    let features = public_features(package);
    let feature_csv = features.join(",");
    let mut sections: Vec<(&str, Vec<&str>)> =
      vec![("default features", vec![])];
    if all_features_section {
      sections.push((
        "all features except _*",
        if features.is_empty() {
          vec![]
        } else {
          vec!["--features", &feature_csv]
        },
      ));
    }

    let mut doc = String::new();
    doc.push_str(&format!(
            "# {package} public API surface\n\
             # Generated by tests/public_api_doc.rs via `cargo public-api --simplified`\n\
             # (regenerated on every `cargo test`; ZEN_API_DOC=check verifies, =off skips).\n"
        ));
    if all_features_section {
      doc.push_str(
        "# Underscore-prefixed features are internal and excluded from the\n\
                 # all-features section.\n",
      );
    } else {
      doc.push_str(
                "# Default-features-only snapshot: decode_test/decode_test_dav1d link\n\
                 # system libaom/libdav1d, `capi` is excluded from the published\n\
                 # package, and `bench` is internal-only (see tests/public_api_doc.rs).\n",
            );
    }
    doc.push_str(
            "# DO NOT EDIT BY HAND — commit regenerated changes together with the code.\n",
        );
    for (label, extra) in &sections {
      let items = surface(package, extra);
      doc.push_str(&format!("\n## {label} ({} items)\n\n", items.len()));
      for line in &items {
        doc.push_str(line);
        doc.push('\n');
      }
      eprintln!("{package} [{label}]: {} public items", items.len());
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
      .join("docs/public-api")
      .join(format!("{package}.txt"));
    let existing = std::fs::read_to_string(&path).ok();

    if check {
      assert_eq!(
        existing.as_deref(),
        Some(doc.as_str()),
        "committed public-API snapshot for {package} is stale: run \
                 `cargo test` locally and commit the regenerated {}",
        path.display()
      );
    } else if existing.as_deref() != Some(doc.as_str()) {
      std::fs::create_dir_all(path.parent().unwrap()).unwrap();
      std::fs::write(&path, &doc).unwrap();
      eprintln!("regenerated {} — review and commit the diff", path.display());
    }
  }
}
